server {
  listen 80;

  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/api/;
  }

  location /admin {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/admin/;
  }

  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/admin/;
  }

  location /docs {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000;
  }

  location /redoc {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000;
  }

  location / {
    proxy_pass http://frontend:5173;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    # WebSocket support for HMR
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
