"""add video_presentation

Revision ID: 12ec3a779a7f
Revises: 2c53b8c6b3f5
Create Date: 2024-10-09 16:01:35.994926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ec3a779a7f'
down_revision: Union[str, None] = '2c53b8c6b3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultants', sa.Column('video_presentation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultants', 'video_presentation')
    # ### end Alembic commands ###
