"""add image

Revision ID: 2c53b8c6b3f5
Revises: 25e16d3a26ee
Create Date: 2024-09-28 03:31:50.972864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c53b8c6b3f5'
down_revision: Union[str, None] = '25e16d3a26ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'image')
    # ### end Alembic commands ###
