"""Add document's files

Revision ID: 45c8ef267601
Revises: 144a11c0a11e
Create Date: 2024-11-07 00:30:12.057024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.services.custom_types


# revision identifiers, used by Alembic.
revision: str = '45c8ef267601'
down_revision: Union[str, None] = '144a11c0a11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file', app.services.custom_types.FileType(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file')
    # ### end Alembic commands ###