"""Add new relationships

Revision ID: 52fb79852146
Revises: 25a78d42e7aa
Create Date: 2024-10-09 09:05:16.540475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fb79852146'
down_revision: Union[str, None] = '25a78d42e7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_date', sa.Date(), nullable=False))
    op.add_column('messages', sa.Column('text', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'records', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('messages', 'text')
    op.drop_column('messages', 'message_date')
    # ### end Alembic commands ###