"""add duration

Revision ID: 65da4fc0e622
Revises: e79f0cd38182
Create Date: 2024-10-30 01:47:27.440465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65da4fc0e622'
down_revision: Union[str, None] = 'e79f0cd38182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration', sa.Interval(), server_default='30 minutes', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'duration')
    # ### end Alembic commands ###
