"""Consultants speciality

Revision ID: 68db6a13a828
Revises: 45c8ef267601
Create Date: 2024-11-08 03:05:46.020770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.services.custom_types


# revision identifiers, used by Alembic.
revision: str = '68db6a13a828'
down_revision: Union[str, None] = '45c8ef267601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speciality',
    sa.Column('speciality', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speciality')
    # ### end Alembic commands ###