"""extra fields to Consultants

Revision ID: 771d9de2918e
Revises: 70c4e3b1d54d
Create Date: 2024-09-14 16:22:13.832679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771d9de2918e'
down_revision: Union[str, None] = '70c4e3b1d54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultants', sa.Column('speciality', sa.Text(), nullable=False))
    op.add_column('consultants', sa.Column('experience', sa.Text(), nullable=False))
    op.add_column('consultants', sa.Column('institution', sa.Text(), nullable=False))
    op.add_column('consultants', sa.Column('current_work', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultants', 'current_work')
    op.drop_column('consultants', 'institution')
    op.drop_column('consultants', 'experience')
    op.drop_column('consultants', 'speciality')
    # ### end Alembic commands ###
