"""Change reviews

Revision ID: 8bac08324b16
Revises: 68db6a13a828
Create Date: 2024-11-09 00:19:35.024387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.services.custom_types


# revision identifiers, used by Alembic.
revision: str = '8bac08324b16'
down_revision: Union[str, None] = '68db6a13a828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('published', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('is_accepted', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'speciality', ['speciality'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'speciality', type_='unique')
    op.drop_column('reviews', 'is_accepted')
    op.drop_column('reviews', 'published')
    # ### end Alembic commands ###