"""Update project

Revision ID: 8e63a4c5161a
Revises: 8fee47609edb
Create Date: 2024-10-29 03:03:51.191760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e63a4c5161a'
down_revision: Union[str, None] = '8fee47609edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('main_problem', sa.Text(), nullable=False),
    sa.Column('bad_habits', sa.Text(), nullable=False),
    sa.Column('allergy', sa.Text(), nullable=False),
    sa.Column('relatives_illnesses', sa.Text(), nullable=False),
    sa.Column('chronic_illnes', sa.Text(), nullable=False),
    sa.Column('user_surgery', sa.Text(), nullable=False),
    sa.Column('for_women', sa.Text(), nullable=True),
    sa.Column('medicament', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('body_parameters', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consultants', sa.Column('video_presentation', sa.Text(), nullable=True))
    op.add_column('consultants', sa.Column('is_accepted', sa.Boolean(), nullable=False))
    op.add_column('consultants', sa.Column('is_send_resume', sa.Boolean(), nullable=False))
    op.alter_column('consultants', 'experience',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('consultants', 'grade',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('cooperations', 'offer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('patients', sa.Column('image', sa.Text(), nullable=True))
    op.alter_column('readstatus', 'last_read_message_id',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readstatus', 'last_read_message_id',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('patients', 'image')
    op.alter_column('cooperations', 'offer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('consultants', 'grade',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('consultants', 'experience',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('consultants', 'is_send_resume')
    op.drop_column('consultants', 'is_accepted')
    op.drop_column('consultants', 'video_presentation')
    op.drop_table('questionnaire')
    # ### end Alembic commands ###